### ISSUE TITLE
setup.py - Broken with pip 10.0.1

### ISSUE THREAD

**Issue by Maceral** [m0ngr31/kodi-voice#27]
When installing for local hosting:
setup.py Line 2 :  `from pip.req import parse_requirements`

Creates an error: 'module not found'

[pip Release notes -10.0.0b1 (2018-03-31)](https://pip.pypa.io/en/stable/news/#b1-2018-03-31)

> Move all of pip's APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs. 

Soultion for pip 10.0.1:
`from pip._internal.req import parse_requirements`

For those setting up as local hosting, hope this helps.

**Comment by m0ngr31** [comment]
Fixed
