### ISSUE TITLE
kodi.config host address

### ISSUE THREAD

**Issue by githu73km** [m0ngr31/kodi-voice#28]
Hi,
When updating the address in the following section of the kodi.config with an IP address 'XXX.XXX.XXX.XXX' the solution works i.e - 

scheme   = http
**address  = 132.125.2.134**
port     = 8888

However when I update the same field, as shown below, with a Dynamic DNS domain name 'kjfhg.khhf.com' this fails and and I get the error 'There was a problem with the requested skill's response' from Alexa.

scheme   = http
**address  = kjfhg.khhf.com**
port     = 8888

Can you please explain why it will work with an IP address but not a Dynamic DNS domain name i obtained from Dynu.

**Comment by jingai** [comment]
Sorry for the incredibly late reply.. but it does work with a FQDN for me.  Did you ever resolve your problem?
